Update coverage.yml

diff --git a/.github/workflows/coverage.yml b/.github/workflows/coverage.yml
--- a/.github/workflows/coverage.yml
+++ b/.github/workflows/coverage.yml
@@ -29,9 +29,19 @@ jobs:
       uses: b3b00/coverlet-action@1.2.5
       with:
         testProject: 'UnitTests/UnitTests.csproj'
-        output: 'lcov.info'
+        output: 'UnitTests/lcov.info'
         outputFormat: 'lcov'
         excludes: '[program]*,[test]test.*'
+
+    - name: Check if lcov.info exists and has content
+      run: |
+        if [ -s "${{ github.workspace }}/UnitTests/lcov.info" ]; then
+          echo "lcov.info exists and is not empty"
+        else
+          echo "Error: lcov.info does not exist or is empty"
+          exit 1
+        fi
+        
     - name: coveralls      
       uses: coverallsapp/github-action@v1.1.1
       with:
