uncommented

diff --git a/.github/workflows/coverage.yml b/.github/workflows/coverage.yml
--- a/.github/workflows/coverage.yml
+++ b/.github/workflows/coverage.yml
@@ -33,17 +33,17 @@ jobs:
         outputFormat: 'lcov'
         excludes: '[program]*,[test]test.*'
 
-#    - name: Check if lcov.info exists and has content
-#      run: |
-#        if [ -s "${{ github.workspace }}/UnitTests/lcov.info" ]; then
-#          echo "lcov.info exists and is not empty"
-#        else
-#          echo "Error: lcov.info does not exist or is empty"
-#          exit 1
-#        fi
-#
-#    - name: Print lcov.info contents
-#      run: cat "${{ github.workspace }}/UnitTests/lcov.info"
+    - name: Check if lcov.info exists and has content
+      run: |
+        if [ -s "${{ github.workspace }}/UnitTests/lcov.info" ]; then
+          echo "lcov.info exists and is not empty"
+        else
+          echo "Error: lcov.info does not exist or is empty"
+          exit 1
+        fi
+
+    - name: Print lcov.info contents
+      run: cat "${{ github.workspace }}/UnitTests/lcov.info"
         
     - name: coveralls      
       uses: coverallsapp/github-action@v1.1.1
